-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. Case Studies Table
create table public.case_studies (
  id text primary key, -- using text ids like 'jpmorgan' for readable URLs
  client text not null,
  category text not null,
  headline text not null,
  image text not null,
  challenge text not null,
  solution text not null,
  results text not null,
  full_description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- JSONB column for flexible stats storage (e.g., [{label: "Savings", value: "50%"}])
alter table public.case_studies add column stats jsonb default '[]'::jsonb;

-- 2. Resources / Library Items
create table public.library_items (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('whitepaper', 'workflow', 'education', 'forms', 'all')),
  title text not null,
  description text not null,
  read_time text not null,
  date date default current_date,
  coming_soon boolean default false,
  file_url text, -- Optional link to the actual resource
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Downloadable Assets
create table public.downloadable_items (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  size text not null,
  type text not null, -- PDF, DOCX
  is_premium boolean default false,
  coming_soon boolean default false,
  download_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Blog Posts
create table public.blog_posts (
  id bigint generated by default as identity primary key,
  title text not null,
  excerpt text not null,
  category text not null,
  read_time text not null,
  image text not null,
  content text, -- HTML or Markdown content
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Row Level Security (RLS) - Optional but recommended
-- Enable read access for everyone
alter table public.case_studies enable row level security;
create policy "Public case studies are viewable by everyone" on public.case_studies for select using (true);

alter table public.library_items enable row level security;
create policy "Public library items are viewable by everyone" on public.library_items for select using (true);

alter table public.downloadable_items enable row level security;
create policy "Public downloads are viewable by everyone" on public.downloadable_items for select using (true);

alter table public.blog_posts enable row level security;
create policy "Public blog posts are viewable by everyone" on public.blog_posts for select using (true);
