-- Blog Analytics Table (for tracking detailed engagement)
CREATE TABLE public.blog_analytics (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  blog_post_id bigint REFERENCES public.blog_posts(id) ON DELETE CASCADE,
  page_views integer DEFAULT 0,
  unique_visitors integer DEFAULT 0,
  avg_time_on_page integer DEFAULT 0,
  bounce_rate decimal(5,2) DEFAULT 0,
  scroll_depth integer DEFAULT 0,
  social_shares integer DEFAULT 0,
  comments integer DEFAULT 0,
  tracked_date date DEFAULT CURRENT_DATE,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(blog_post_id, tracked_date)
);

-- Editor Reviews Table (audit trail for QC)
CREATE TABLE public.editor_reviews (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  blog_post_id bigint REFERENCES public.blog_posts(id) ON DELETE CASCADE,
  review_type text NOT NULL CHECK (review_type IN ('fact_check', 'seo_audit', 'brand_voice', 'engagement', 'full_review')),
  original_content text,
  edited_content text,
  issues_found jsonb DEFAULT '[]'::jsonb,
  corrections_made jsonb DEFAULT '[]'::jsonb,
  score integer DEFAULT 0 CHECK (score >= 0 AND score <= 100),
  ai_reasoning text,
  reviewed_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Topic Recommendations Table (AI-suggested topics)
CREATE TABLE public.topic_recommendations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  topic_title text NOT NULL,
  category text NOT NULL,
  reasoning text,
  trending_score integer DEFAULT 0,
  similar_to_post_id bigint REFERENCES public.blog_posts(id) ON DELETE SET NULL,
  keywords text[] DEFAULT '{}',
  status text DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'published')),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Brand Voice Profile Table (stores Substack voice patterns)
CREATE TABLE public.brand_voice_profile (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source text NOT NULL DEFAULT 'substack',
  key_phrases text[] DEFAULT '{}',
  tone_descriptors text[] DEFAULT '{}',
  forbidden_terms text[] DEFAULT '{}',
  writing_style_notes text,
  example_excerpts jsonb DEFAULT '[]'::jsonb,
  topics_covered text[] DEFAULT '{}',
  last_synced_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.blog_analytics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.editor_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.topic_recommendations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.brand_voice_profile ENABLE ROW LEVEL SECURITY;

-- Public read policies
CREATE POLICY "Public can view blog analytics" ON public.blog_analytics FOR SELECT USING (true);
CREATE POLICY "Public can view topic recommendations" ON public.topic_recommendations FOR SELECT USING (true);
CREATE POLICY "Public can view brand voice profile" ON public.brand_voice_profile FOR SELECT USING (true);
CREATE POLICY "Public can view editor reviews" ON public.editor_reviews FOR SELECT USING (true);

-- Service role insert/update policies
CREATE POLICY "Service can insert blog analytics" ON public.blog_analytics FOR INSERT WITH CHECK (true);
CREATE POLICY "Service can update blog analytics" ON public.blog_analytics FOR UPDATE USING (true);
CREATE POLICY "Service can insert editor reviews" ON public.editor_reviews FOR INSERT WITH CHECK (true);
CREATE POLICY "Service can update editor reviews" ON public.editor_reviews FOR UPDATE USING (true);
CREATE POLICY "Service can insert topic recommendations" ON public.topic_recommendations FOR INSERT WITH CHECK (true);
CREATE POLICY "Service can update topic recommendations" ON public.topic_recommendations FOR UPDATE USING (true);
CREATE POLICY "Service can insert brand voice profile" ON public.brand_voice_profile FOR INSERT WITH CHECK (true);
CREATE POLICY "Service can update brand voice profile" ON public.brand_voice_profile FOR UPDATE USING (true);