-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. Case Studies Table
create table public.case_studies (
  id text primary key,
  client text not null,
  category text not null,
  headline text not null,
  image text not null,
  challenge text not null,
  solution text not null,
  results text not null,
  full_description text,
  stats jsonb default '[]'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Resources / Library Items
create table public.library_items (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('whitepaper', 'workflow', 'education', 'forms', 'all')),
  title text not null,
  description text not null,
  read_time text not null,
  date date default current_date,
  coming_soon boolean default false,
  file_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Downloadable Assets
create table public.downloadable_items (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  size text not null,
  type text not null,
  is_premium boolean default false,
  coming_soon boolean default false,
  download_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Blog Posts
create table public.blog_posts (
  id bigint generated by default as identity primary key,
  title text not null,
  excerpt text not null,
  category text not null,
  read_time text not null,
  image text not null,
  content text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Contact Form Submissions
create table public.contact_submissions (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  email text not null,
  company text,
  area_of_interest text,
  message text not null,
  source text not null check (source in ('contact', 'consultation')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on all tables
alter table public.case_studies enable row level security;
alter table public.library_items enable row level security;
alter table public.downloadable_items enable row level security;
alter table public.blog_posts enable row level security;
alter table public.contact_submissions enable row level security;

-- Public read policies
create policy "Public case studies are viewable by everyone" 
  on public.case_studies for select using (true);

create policy "Public library items are viewable by everyone" 
  on public.library_items for select using (true);

create policy "Public downloads are viewable by everyone" 
  on public.downloadable_items for select using (true);

create policy "Public blog posts are viewable by everyone" 
  on public.blog_posts for select using (true);

-- Contact submissions should only be viewable by authenticated admins
create policy "Only authenticated users can view contact submissions" 
  on public.contact_submissions for select 
  to authenticated using (true);